# Generated by Django 3.0.6 on 2020-05-27 17:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambito',
            fields=[
                ('Id', models.AutoField(db_column='AM_Id_Ambito', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='AM_Nombre', max_length=256)),
                ('Descripcion', models.CharField(blank=True, db_column='AM_Descripcion', max_length=256, null=True)),
                ('Eliminado', models.BooleanField(db_column='AM_Eliminado', default=False)),
            ],
            options={
                'db_table': 'ambitos',
            },
        ),
        migrations.CreateModel(
            name='AreaGeografica',
            fields=[
                ('Id', models.AutoField(db_column='AG_Id_Area_Geo', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='AG_Nombre', max_length=256)),
                ('Descripcion', models.CharField(blank=True, db_column='AG_Descripcion', max_length=256, null=True)),
                ('Eliminado', models.BooleanField(db_column='AG_Eliminado', default=False)),
            ],
            options={
                'db_table': 'areas_geograficas',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('Id', models.AutoField(db_column='EM_Id_Empresa', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='EM_Nombre', max_length=256)),
                ('Descripcion', models.CharField(blank=True, db_column='EM_Descripcion', max_length=256, null=True)),
                ('Eliminado', models.BooleanField(db_column='EM_Eliminado', default=False)),
                ('IdAg', models.ForeignKey(blank=True, db_column='Em_Centro_Principal', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.AreaGeografica')),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('Id', models.AutoField(db_column='MD_Id_Modelo', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='MD_Nombre', max_length=256)),
                ('Descripcion', models.CharField(blank=True, db_column='MD_Descripcion', max_length=256, null=True)),
                ('Eliminado', models.BooleanField(db_column='MD_Eliminado', default=False)),
                ('IdEmp', models.ForeignKey(db_column='MD_Id_Empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Empresa')),
            ],
            options={
                'db_table': 'modelos',
            },
        ),
        migrations.CreateModel(
            name='NivelAreaGeografica',
            fields=[
                ('Id', models.AutoField(db_column='NG_Id_Nivel_Area_Geo', primary_key=True, serialize=False)),
                ('Nivel', models.IntegerField(db_column='NG_Nivel', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('Nombre', models.CharField(db_column='NG_Nombre', max_length=256)),
                ('Descripcion', models.CharField(blank=True, db_column='NG_Descripcion', max_length=256, null=True)),
                ('Eliminado', models.BooleanField(db_column='NG_Eliminado', default=False)),
            ],
            options={
                'db_table': 'nivel_areas_geograficas',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('Id', models.AutoField(db_column='SC_Id_Sector', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='SC_Nombre', max_length=256)),
                ('Descripcion', models.CharField(blank=True, db_column='SC_Descripcion', max_length=256, null=True)),
                ('Eliminado', models.BooleanField(db_column='SC_Eliminado', default=False)),
            ],
            options={
                'db_table': 'sectores',
            },
        ),
        migrations.CreateModel(
            name='TipoObjetivo',
            fields=[
                ('Id', models.AutoField(db_column='TO_Id_Tipo_Objetivo', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='TO_Nombre', max_length=256)),
                ('Eliminado', models.BooleanField(db_column='TO_Eliminado', default=False)),
            ],
            options={
                'db_table': 'tipos_objetivos',
            },
        ),
        migrations.CreateModel(
            name='PuntosCapitulo',
            fields=[
                ('Id', models.AutoField(db_column='CP_Id_Capitulo', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='CP_Nombre', max_length=256)),
                ('descripcion', models.CharField(blank=True, db_column='CP_Descripcion', max_length=256, null=True)),
                ('Eliminado', models.BooleanField(db_column='CP_Eliminado', default=False)),
                ('IdAm', models.ForeignKey(db_column='CP_Id_Ambito', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Ambito')),
                ('IdMd', models.ForeignKey(db_column='CP_Id_Modelo', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Modelo')),
            ],
            options={
                'db_table': 'puntos_capitulos',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('Id', models.AutoField(db_column='OB_Id_Objetivo', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='OB_Nombre', max_length=256)),
                ('Descripcion', models.CharField(blank=True, db_column='OB_Descripcion', max_length=256, null=True)),
                ('Codificacion', models.CharField(db_column='OB_Codificacion', max_length=256)),
                ('Anyo', models.IntegerField(blank=True, db_column='OB_Año', null=True)),
                ('Eliminado', models.BooleanField(db_column='OB_Eliminado', default=False)),
                ('IdParent', models.ForeignKey(db_column='OB_Id_Objetivo_Padre', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Objetivo')),
                ('IdPc', models.ForeignKey(db_column='OB_Id_Capitulo', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.PuntosCapitulo')),
                ('IdTo', models.ForeignKey(db_column='OB_Id_Tipo_Objetivo', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.TipoObjetivo')),
            ],
            options={
                'db_table': 'objetivos',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='IdSc',
            field=models.ForeignKey(db_column='EM_Id_Sector', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Sector'),
        ),
        migrations.CreateModel(
            name='Benchmarking',
            fields=[
                ('Id', models.AutoField(db_column='BH_Id_Bench', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='BH_Nombre', max_length=256)),
                ('Descripcion', models.CharField(blank=True, db_column='BH_Descripcion', max_length=256, null=True)),
                ('Valor', models.IntegerField(blank=True, db_column='BH_Valor', null=True)),
                ('Anyo', models.IntegerField(blank=True, db_column='BH_Año', null=True)),
                ('Ciclo', models.CharField(blank=True, db_column='BH_Ciclo', max_length=256, null=True)),
                ('Eliminado', models.BooleanField(db_column='BH_Eliminado', default=False)),
                ('IdAg', models.ForeignKey(db_column='BH_Id_Area_Geo', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.AreaGeografica')),
                ('IdSc', models.ForeignKey(db_column='BH_Id_Sector', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Sector')),
            ],
            options={
                'db_table': 'benchmarkings',
            },
        ),
        migrations.AddField(
            model_name='areageografica',
            name='IdNag',
            field=models.ForeignKey(db_column='AG_Id_Nivel', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.NivelAreaGeografica'),
        ),
        migrations.AddField(
            model_name='areageografica',
            name='IdParent',
            field=models.ForeignKey(blank=True, db_column='AG_Id_Area_Padre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.AreaGeografica'),
        ),
    ]
