# Generated by Django 3.0.6 on 2020-05-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntoscapitulo',
            old_name='descripcion',
            new_name='Descripcion',
        ),
    ]
