# Generated by Django 3.0.6 on 2020-05-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0002_auto_20200529_1047'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sector',
            table='T_Sector',
        ),
    ]
