# Generated by Django 3.0.6 on 2020-05-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0003_auto_20200530_2156'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ambito',
            table='T_Ambitos',
        ),
        migrations.AlterModelTable(
            name='areageografica',
            table='T_Area_Geografica',
        ),
        migrations.AlterModelTable(
            name='benchmarking',
            table='T_Benchmarkig',
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='T_Empresa',
        ),
        migrations.AlterModelTable(
            name='modelo',
            table='T_Modelo',
        ),
        migrations.AlterModelTable(
            name='nivelareageografica',
            table='T_Nivel_Area_Geografica',
        ),
        migrations.AlterModelTable(
            name='objetivo',
            table='T_Objetivo',
        ),
        migrations.AlterModelTable(
            name='puntoscapitulo',
            table='T_Puntos_Capitulo',
        ),
        migrations.AlterModelTable(
            name='tipoobjetivo',
            table='T_Tipo_Objetivo',
        ),
    ]
