# Generated by Django 3.0.6 on 2020-05-30 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0004_auto_20200530_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='IdAg',
            field=models.ForeignKey(db_column='Em_Centro_Principal', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.AreaGeografica'),
        ),
    ]
