# Generated by Django 3.0.6 on 2020-06-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0006_auto_20200601_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionmeta',
            name='Eliminado',
            field=models.BooleanField(db_column='AT_Eliminado', default=False),
        ),
        migrations.AddField(
            model_name='documentossistema',
            name='Eliminado',
            field=models.BooleanField(db_column='DC_Eliminado', default=False),
        ),
        migrations.AddField(
            model_name='indicadoraccionproceso',
            name='Eliminado',
            field=models.BooleanField(db_column='IA_Eliminado', default=False),
        ),
        migrations.AddField(
            model_name='meta',
            name='Eliminado',
            field=models.BooleanField(db_column='MT_Eliminado', default=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='Eliminado',
            field=models.BooleanField(db_column='PR_Eliminado', default=False),
        ),
        migrations.AddField(
            model_name='seguimientoindicadores',
            name='Eliminado',
            field=models.BooleanField(db_column='IS_Eliminado', default=False),
        ),
    ]
