# Generated by Django 3.0.6 on 2020-06-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0008_auto_20200601_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadoraccionproceso',
            name='IdProc',
            field=models.ForeignKey(blank=True, db_column='IA_Id_Proceso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Proceso'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='IdParent',
            field=models.ForeignKey(blank=True, db_column='OB_Id_Objetivo_Padre', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Objetivo'),
        ),
    ]
