# Generated by Django 3.0.6 on 2020-06-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0010_auto_20200601_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadoraccionproceso',
            name='IdProc',
            field=models.ForeignKey(blank=True, db_column='IA_Id_Proceso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Proceso'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='IdParent',
            field=models.ForeignKey(blank=True, db_column='MT_Id_Padre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Meta'),
        ),
    ]
