# Generated by Django 3.0.6 on 2020-06-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0012_auto_20200604_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoobjetivo',
            name='Descripcion',
            field=models.CharField(blank=True, db_column='TO_Descripcion', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='indicadoraccionproceso',
            name='IdProc',
            field=models.ForeignKey(blank=True, db_column='IA_Id_Proceso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Proceso'),
        ),
        migrations.AlterField(
            model_name='indicadoraccionproceso',
            name='Plazo',
            field=models.CharField(choices=[('Semanal', 'Semanal'), ('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Bimestral', 'Bimestral'), ('Cuatrimestral', 'Cuatrimestral'), ('Semetral', 'Semestral'), ('Anual', 'Anual')], db_column='IA_Plazo_Seguimiento', max_length=256),
        ),
    ]
