# Generated by Django 3.0.6 on 2020-06-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsMaster', '0015_auto_20200609_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentossistema',
            name='Descripcion',
            field=models.CharField(blank=True, db_column='DC_Descripcion', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='indicadoraccionproceso',
            name='IdProc',
            field=models.ForeignKey(blank=True, db_column='IA_Id_Proceso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Proceso'),
        ),
    ]
