# Generated by Django 3.0.6 on 2020-06-14 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('ModelsMaster', '0016_auto_20200614_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadoraccionproceso',
            name='IdProc',
            field=models.ForeignKey(blank=True, db_column='IA_Id_Proceso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Proceso'),
        ),
        migrations.CreateModel(
            name='UserEmpresa',
            fields=[
                ('Id', models.AutoField(db_column='UE_Id_UserEmpresa', primary_key=True, serialize=False)),
                ('Eliminado', models.BooleanField(db_column='UE_Eliminado', default=False)),
                ('IdEmp', models.ForeignKey(db_column='UE_Id_Empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Empresa')),
                ('IdUser', models.ForeignKey(db_column='UE_Id_Usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'T_User_Empresa',
            },
        ),
        migrations.CreateModel(
            name='GroupEmpresa',
            fields=[
                ('Id', models.AutoField(db_column='GE_Id_GroupEmpresa', primary_key=True, serialize=False)),
                ('Eliminado', models.BooleanField(db_column='GE_Eliminado', default=False)),
                ('IdEmp', models.ForeignKey(db_column='GE_Id_Empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='ModelsMaster.Empresa')),
                ('IdGroup', models.ForeignKey(db_column='GE_Id_Group', on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group')),
            ],
            options={
                'db_table': 'T_Group_Empresa',
            },
        ),
    ]
